#!/bin/bash -e

BASE_DIR=/var/vcap/packages/greenplum-server/gpdb/greenplum-db
LOG_DIR=/var/vcap/sys/log/greenplum-db
DATA_DIR=/data/master
PIDFILE=$DATA_DIR/gpseg-1/postmaster.pid

source /var/vcap/packages/common/utils.sh  
case $1 in
  start)


    PROP_DIR=`dirname "$0"`
    PROP_DIR=$PROP_DIR/../config/
    mkdir -p $LOG_DIR
    
    HOST_FILE=$PROP_DIR/hosts

    # Remove blank lines
    sed '/^$/d' $HOST_FILE > /tmp/all_hosts
   
    HOST_FILE=/tmp/all_hosts 

    if ! test -d $DATA_DIR; then
        
        

	# SU
	#echo 'c1oudc0w' | sudo -S su - ; sudo su -
	sudo su -

	# INSTALL

	#enable root ssh login
        sed -i 's/#PermitRootLogin/PermitRootLogin/g' /etc/ssh/sshd_config
        service restart sshd

        source $BASE_DIR/greenplum_path.sh
	gpseginstall -f $PROP_DIR/hostfile_gpinitsystem -u gpadmin -p gpadmin >> $LOG_DIR/gpseginstall.log
        
        #useradd -m  gpadmin;echo 'gpadmin'|passwd --stdin gpadmin
        #chown -R gpadmin:gpadmin $BASE_DIR
        

        #chown gpadmin:gpadmin $PROP_DIR/run_install.sh
        #cp $PROP_DIR/run_install.sh /tmp
        #chmod -R a+rx /tmp

        #NUMBER_OF_HOSTS=`more $HOST_FILE|wc -l`
        #su - gpadmin
        #source $BASE_DIR/greenplum_path.sh
        #/tmp/run_install.sh $HOST_FILE $LOG_DIR gpadmin 

	# INITIALIZE DATA DIRS
	mkdir -p $DATA_DIR
	chown gpadmin $DATA_DIR
	gpssh -f $PROP_DIR/hostfile_gpinitsystem -e 'mkdir /data1/primary;chown gpadmin /data1/primary'
	gpssh -f $PROP_DIR/hostfile_gpinitsystem -e 'mkdir /data2/primary;chown gpadmin /data2/primary'
        
        # generate SSH trust 
        MASTER_HOSTNAME=`hostname` 
        echo $MASTER_HOSTNAME >> $HOST_FILE
        gpssh -f $HOST_FILE 'hostname'|sed s/[[][0-9]*.[0-9]*.[0.9]*.[0-9]*[]].//  >> $HOST_FILE

        gpssh-exkeys -f $HOST_FILE

        # init DB
        su - gpadmin
	source $BASE_DIR/greenplum_path.sh
        # Remove blank lines
        sed '/^$/d' $PROP_DIR/gpinitsystem_config > /tmp/segment_hosts
	gpinitsystem -a -c $PROP_DIR/gpinitsystem_config -h /tmp/segment_hosts -l ${LOG_DIR}
    fi


    pid_guard $PIDFILE "greenplum"

    su - gpadmin
    gpstart -a -l ${LOG_DIR} -q

    

    ;;

  stop)
    
    gpstop -a -l ${LOG_DIR} -M fast
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: master_ctl {start|stop}"

    ;;

esac
